# Site settings
title: FoodSpan
email: matthew.wang@ucc.on.ca
description: >
  FoodSpan is an amazing service!
baseurl: "/foodspan"
url: "http://matthewwang.me/foodspan"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
exclude: [vendor]

# collections

collections:
  shop:
    output: true
