# Site settings
title: FoodSpan
email: matt@matthewwang.me
description: >
  FoodSpan works in your kitchen to help you save food, time, and money, simply by swiping and attaching a tag. Not only does your leftover spaghetti not become a science experiment, but you can save hundreds of dollars every year! Plus, FoodSpan is always available using our suite of web and mobile applications, so you always know what's cool in your fridge.
baseurl: ""
url: "https://foodspan.github.io"
webspanurl: "https://matthewwang.me/foodspan-website/webspan/"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
exclude: [vendor]

# collections

collections:
  shop:
    output: true
