# Site settings
title: FoodSpan
email: matthew.wang@ucc.on.ca
description: > 
  FoodSpan is an amazing service!
baseurl: "/foodspan"
url: "http://matthewwang.me/foodspan"
twitter_username: malsf21
github_username:  malsf21

# Build settings
markdown: kramdown
kramdown:
  input: GFM
exclude: [vendor]

# plugins
gems: [jekyll-paginate]
paginate: 10

# collections

collections:
  shop:
    output: true
